"""A Backtest v2 row -> the strategy key and spec the runner trades it by.

The rule the Sep 24/25/27 blocks in auto_trader.py were generated by ("GENERATED
FROM THE MEASURED ROWS, never typed"): tp/sl are the row's own percents over
100, interval/bar_seconds come from its timeframe, and `threshold` is the row's
th for the rules that read one, in the NAME too (`_t08_`). A percent of 10 or
more is written `12p0`, because `tp12` already means 1.2%.
"""
from __future__ import annotations

TF_SPEC = {"15m": ("Min15", 900), "30m": ("Min30", 1800),
           "1h": ("Min60", 3600), "4h": ("Hour4", 14400),
           "1d": ("Day1", 86400)}
THRESHOLD_SIGNALS = ("mom6", "mom15", "fade15")


def pct_code(pct: float) -> str:
    s = f"{float(pct):g}"
    if float(pct) >= 10:
        return s.replace(".", "p") if "." in s else s + "p0"
    return s.replace(".", "")


def key_for(row: dict) -> str:
    tf = str(row["tf"])
    if tf not in TF_SPEC:
        raise ValueError(f"the runner cannot trade timeframe {tf!r}")
    parts = [str(row["signal"]), tf]
    if row["signal"] in THRESHOLD_SIGNALS:
        parts.append("t" + pct_code(row["th"]))
    parts.append(f"sl{pct_code(row['sl'])}tp{pct_code(row['tp'])}")
    return "_".join(parts)


def spec_for(row: dict) -> dict:
    interval, secs = TF_SPEC[str(row["tf"])]
    spec = {"interval": interval, "bar_seconds": secs,
            "tp": round(float(row["tp"]) / 100, 6),
            "sl": round(float(row["sl"]) / 100, 6)}
    if row["signal"] in THRESHOLD_SIGNALS:
        spec["threshold"] = round(float(row["th"]) / 100, 6)
    return spec
