import { chromium } from 'playwright';
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1680, height: 1050 } });
await p.goto('http://localhost:8507', { waitUntil: 'networkidle' });
await p.waitForTimeout(9000);
await p.locator('text=Backtest 2').first().click();
await p.waitForTimeout(8000);
console.log('buttons:', JSON.stringify(await p.locator('button').allInnerTexts()));
const t = await p.locator('body').innerText();
console.log('page text head:', t.slice(0, 400).replace(/\n+/g, ' | '));
await p.screenshot({ path: '/tmp/bt2_probe.png' });
await b.close();
