import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1680, height: 1050 } });
await page.goto('http://localhost:8503', { waitUntil: 'networkidle' });
await page.waitForTimeout(8000);
await page.locator('text=Auto Trade').first().click();
await page.waitForTimeout(25000);
const body = await page.locator('body').innerText();
const heads = ["contract","unreal $","to TP","TP % ($)","SL % ($)","side","opened","held","entry","margin","bracket"];
const missing = heads.filter(h => !body.toLowerCase().includes(h.toLowerCase()));
console.log('missing headers:', missing.length ? missing : 'none — all 14-column headers present');
await page.screenshot({ path: '/tmp/pos_cols.png', fullPage: false });
await browser.close();
